# docker-compose up -d ?
version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    #~environment
    ports:
      - "5432:5432"
    #~ports
    volumes:
      - pgdata:/var/lib/postgresql/data
    #~volumes
  #~db
#~services

volumes:
  pgdata:
