@Ngaq.Server.Http_HostAddress = http://localhost:5178

GET {{Ngaq.Server.Http_HostAddress}}/todos/
Accept: application/json

###

GET {{Ngaq.Server.Http_HostAddress}}/todos/1
Accept: application/json

###
